---

- name: disable supervisord service
  service:
    name: supervisord
    state: stopped
    enabled: no

- name: delete supervisord init script
  file:
    name: /etc/rc.d/init.d/supervisord
    state: absent

- name: delete supervisord config
  file:
    name: /etc/supervisord.conf
    state: absent

- name: create supervisord service dir
  file:
    name: /etc/supervisord.conf.d
    state: directory
    mode: 0755

