---
- name: uninstall supervisord (yum)
  yum:
    name: supervisor
    state: absent
  when: ansible_distribution == 'CentOS'

- name: install python-meld3
  yum:
    name: python-meld3
    state: installed
  when: ansible_distribution == 'CentOS'

- name: install supervisord (pip)
  pip:
    name: supervisor
    state: present
    version: 3.3

- name: create supervisord service dir
  file:
    name: /etc/supervisord.conf.d
    state: directory
    mode: 0755

- name: create /var/log/supervisor
  file:
    name: /var/log/supervisor
    state: directory
    mode: 0700

#- name: ensure supervisord is running and enabled
#  service:
#    name: supervisord
#    state: started
#    enabled: yes
