---
  # Set up user and group

  - name: create group apis
    group:
      name: apis
      state: present

  - name: check if modify user password or not
    fail:
      msg: "Please enter a new password for osu_apis!"
    when: user_password == "password"

  - name: create user osu_apis
    user:
      name: osu_apis
      comment: "OSU APIs"
      group: apis
      password: "{{ user_password }}"

  # Create directories

  - name: create apis directory structure
    file:
      path: '{{ item }}'
      state: directory
      group: apis
      owner: osu_apis
      mode: 0770
    with_items:
      - /apis
      - /apis/apis
      - /apis/config
      - /apis/logs
      - /apis/run.d

  - name: create /apis/keytool_files directory
    file:
      path: "{{ item }}"
      state: directory
      group: apis
      owner: osu_apis
      mode: 0555
    with_items:
      - /apis/keytool_files
      - /apis/keytool_files/backup

  # Install supervisor

  - name: create /apis/supervisor directory
    file:
      path: /apis/supervisor
      state: directory
      group: apis
      owner: osu_apis
      mode: 0750

  - name: install config file for the api supervisor
    copy:
      src: supervisord.conf
      dest: /apis/supervisor/supervisord.conf
      group: apis
      owner: osu_apis
      mode: 0644

  - name: copy api job template
    copy:
      src: api-service-template.conf
      dest: /apis/run.d/template
      group: apis
      owner: osu_apis
      mode: 0644

  - name: copy scripts
    copy:
      src: '{{ item }}'
      dest: '/apis/{{ item }}'
      group: apis
      owner: osu_apis
      mode: 0754
    with_items:
      - jenkins-run.sh
      - supervisord-run.sh

  - name: install api_supervisor service
    copy:
      src: api_supervisor.service
      dest: /etc/systemd/system/api_supervisor.service
      owner: root
      group: root
      mode: 0644

  - name: ensure the api supervisor is started
    service:
      name: api_supervisor
      state: started
      enabled: true
