---

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: installed
    update_cache: true

- name: add docker repo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo debian-{{ansible_distribution_release}} main'
    filename: docker
    state: present

- name: add docker key
  apt_key:
    id: '58118E89F3A912897C070ADBF76221572C52609D'
    data: "{{ lookup('file', 'docker.gpg') }}"
    state: present

- name: install docker
  apt:
    name: docker-engine
    state: installed
    update_cache: true

- name: enable docker service
  service:
    name: docker
    enabled: yes
    state: started

# install pip to allow use of docker image and container ansible module

- name: install pip
  apt:
    name: python-pip
    state: present
