---

- name: CentOS
  include: centos.yml
  when: 'ansible_distribution == "CentOS"'

- name: Debian
  include: debian.yml
  when: 'ansible_distribution == "Debian"'

# Kind of like doing update_cache for apt. Issue: https://github.com/ansible/ansible/issues/10810
- name: Make sure pip upgraded
  command: easy_install -U pip
  tags:
    - skip_ansible_lint

- name: install docker tools
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
