---

- name: CentOS
  include: centos.yml
  when: 'ansible_distribution == "CentOS"'

- name: Debian
  include: debian.yml
  when: 'ansible_distribution == "Debian"'

# Kind of like doing update_cache for apt. Issue: https://github.com/ansible/ansible/issues/10810
- name: Make sure pip upgraded
  command: easy_install -U pip
  tags:
    - skip_ansible_lint

# Install old version of docker-compose, workaround for ansible issue https://github.com/ansible/ansible/issues/20492
- name: install docker tools
  pip:
    name: "docker-compose"
    state: present
    version: "1.9.0"
