---

- name: CentOS
  include: centos.yml
  when: 'ansible_distribution == "CentOS"'

- name: Debian
  include: debian.yml
  when: 'ansible_distribution == "Debian"'

# Kind of like doing update_cache for apt. Issue: https://github.com/ansible/ansible/issues/10810
- name: Make sure pip upgraded
  command: easy_install -U pip
  tags:
    - skip_ansible_lint

- name: install docker-py
  pip:
    name: docker-py
    state: present
    version: 1.9.0 # Ansible bug workaround. Issue: https://github.com/ansible/ansible/issues/17495