---
  - name: install OpenJDK 8 (CentOS)
    yum:
      name: java-1.8.0-openjdk-devel
    when: ansible_distribution == 'CentOS'

  - name: add backports repo (Debian Jessie)
    apt_repository:
      repo: 'deb http://ftp.debian.org/debian jessie-backports main'
      state: present
    when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

  - name: update ca-certificates-java (Debian Jessie)
    apt:
      name: ca-certificates-java
      default_release: jessie-backports
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'
    tags:
      - skip_ansible_lint

  - name: install OpenJDK 8 (Debian)
    apt:
      name: openjdk-8-jdk
      update_cache: yes
    when: ansible_distribution == 'Debian'
